### ISSUE TITLE
Trackpad gestures and scrolling unresponsive after sleep

### ISSUE THREAD

**Issue by Notsobrightguy** [yusufklncc/Lenovo-Thinkpad-Yoga-S1-Hackintosh#2]
After waking from sleep, trackpad still works but two finger scrolling isn't working.  Two finger taps also don't work.  Other than that, everything seems smooth as butter.

Thank you for uploading this EFI config here.  I appreciate all your effort.

**Comment by yusufklncc** [comment]
Did you solve issue?

**Comment by Notsobrightguy** [comment]
Yes I actually did. I cannot quite remember what I did but with digging I can fine my notes somewhere. Else I can send my EFI if you want it.Sent from my iPhoneOn 04 Nov 2022, at 17:02, Yusuf İhsan KILINÇ ***@***.***> wrote:﻿
Did you solve issue?

**Comment by yusufklncc** [comment]
Please. Thank you. I'll look and try to find it. But I no longer use this computer. I'll just look at the differences.

**Comment by Notsobrightguy** [comment]
I have uploaded my OC folder to Dropbox.  

https://www.dropbox.com/s/njm76yjc6rlrsll/OC.zip?dl=0

According to my notes, the solution boiled dow to using VoodooRMI.  Maybe you can share the fix so others too can benefit.  Thanks a million for your efforts.

**Comment by yusufklncc** [comment]
Hey, I updated the EFI. do you have a chance to test it

**Comment by Notsobrightguy** [comment]
Hey man.  I haven’t had a ton of time to test it but the little that I have, it looks like it’s working great.

 

From: Yusuf İhsan KILINÇ ***@***.***>
Reply to: yusufklncc/Lenovo-Thinkpad-Yoga-S1-Hackintosh ***@***.***>
Date: Sunday, 06 November 2022 at 17:38
To: yusufklncc/Lenovo-Thinkpad-Yoga-S1-Hackintosh ***@***.***>
Cc: Notsobrightguy ***@***.***>, Author ***@***.***>
Subject: Re: [yusufklncc/Lenovo-Thinkpad-Yoga-S1-Hackintosh] Trackpad gestures and scrolling unresponsive after sleep (Issue #2)

 

Hey, I updated the EFI. do you have a chance to test it

**Comment by yusufklncc** [comment]
okay thanks :)
