### ISSUE TITLE
Horizon lines during boot

### ISSUE THREAD

**Issue by jay448** [yusufklncc/Lenovo-Thinkpad-Yoga-S1-Hackintosh#3]
Hi, 

I'm running a Lenovo ThinkPad Yoga S1 20c0 and when starting the installer I can see the following lines in my screen:
![IMG_0278](https://user-images.githubusercontent.com/1663401/202706258-0c84229d-8499-4340-bdbd-2d065511fa84.jpg)

I've used the config.plist for the touchscreen version since I am running that one.

I'm new to the whole hack-in-tosh think and I'm wondering if you could point me in the right direction.

Let me know! 
Thanks :)

**Comment by yusufklncc** [comment]
Change CSM setting in bios. Try on/off. Use last efi.

**Comment by yusufklncc** [comment]
@jay448

**Comment by aldrockhavana** [comment]
I had the same issue, I put CSM to the YES option, it fixes the lines at boot
