### ISSUE TITLE
Is it possible to support MacOS 13 Ventura?

### ISSUE THREAD

**Issue by RecordingTheSmile** [yusufklncc/Lenovo-Thinkpad-Yoga-S1-Hackintosh#4]
Thanks for your works to maintain this OpenCore configuration! Recently I am working on modify the OpenCore configuration, trying to run MacOS 13 on this machine just like MacOS 12. But I found if I update to the 13, some important function failed due to apple seems abandon a lot of drivers, like sound, display, etc. So, I wonder is it possible to support MacOS 13?

**Comment by yusufklncc** [comment]
Yep it supports. I updated EFI.
