### ISSUE TITLE
CFG Lock Problem

### ISSUE THREAD

**Issue by ailelix** [yusufklncc/Lenovo-Thinkpad-Yoga-S1-Hackintosh#5]
I try to install Monterey 12.6 on my S1 Yoga

> Prod ID: 20CDS00800
> CPU: i7-4500U
> RAM: DDR3 8GB 1600MT/s
> Network: Intel Wireless 7260
> BIOS: GQET63WW (1.43) 2020/3/24

OS Version: 12.6 21G115 (For OpenCore 0.8.4)
EFI Version: OC 0.8.6

I succeed in booting up to the MacOS Boot-up page
But get stuck to "EXITBS:START" when I install Monterey
I tried to boot to Clover and install
But the install program stopped at around 1/3 with "Broken Installer"
My CFG Lock on 0x79 is enabled (0x01)
I tried both the CFGTool in the mirror and ru.efi to disable it
But it seems to be read-only

**Comment by yusufklncc** [comment]
> I try to install Monterey 12.6 on my S1 Yoga
> 
> > Prod ID: 20CDS00800
> > CPU: i7-4500U
> > RAM: DDR3 8GB 1600MT/s
> > Network: Intel Wireless 7260
> > BIOS: GQET63WW (1.43) 2020/3/24
> 
> OS Version: 12.6 21G115 (For OpenCore 0.8.4) EFI Version: OC 0.8.6
> 
> I succeed in booting up to the MacOS Boot-up page But get stuck to "EXITBS:START" when I install Monterey I tried to boot to Clover and install But the install program stopped at around 1/3 with "Broken Installer" My CFG Lock on 0x79 is enabled (0x01) I tried both the CFGTool in the mirror and ru.efi to disable it But it seems to be read-only

im gonna fix this issue. im having this issue before and gave up :) But now after you wrote. I figure it out something and im in big sur installation screen. After updating EFI i will release it.

**Comment by ailelix** [comment]
I'm also looking for disable it by programmer (idk its name,  maybe PLC?)
Anyway ty for creating and maintaining this efi

**Comment by yusufklncc** [comment]
Yes, Lenovo's BIOS is read-only and you cannot disable CFG-lock, but it is not necessary to do so as it doesn't matter. I am currently installing macOS Monterey. After reaching the desktop in 20 minutes, I will check if there are any errors and then release this EFI.

**Comment by yusufklncc** [comment]
https://github.com/yusufklncc/Lenovo-Thinkpad-Yoga-S1-Hackintosh/releases/tag/v0.8.8
here u go.

**Comment by ailelix** [comment]
Successfully installed and everything seem to work
Thank you for the epic work
![TY](https://i.postimg.cc/zG2xQVtg/7b3eb2a4d38d2a2068e04e0614bda48e.png)

**Comment by yusufklncc** [comment]
@ccxxvv77 https://github.com/yusufklncc/Lenovo-Thinkpad-Yoga-S1-Hackintosh/releases
![68747470733a2f2f692e706f7374696d672e63632f7a473278515674672f37623365623261346433386432613230363865303465303631346264613438652e706e67](https://user-images.githubusercontent.com/78423442/216901769-2fe68d6f-1011-48ce-964c-380fbaff61a7.png)
